# Generated by Django 2.2.4 on 2020-01-27 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoAwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('unit', models.TextField()),
                ('material', models.IntegerField()),
                ('nilai', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='Update Terakhir')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=255, verbose_name='Kode Plant')),
                ('departement', models.CharField(max_length=255, verbose_name='Departemen')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Plant')),
                ('perusahaan', models.CharField(default='PT PETROKIMIA GRESIK', max_length=255, verbose_name='Perusahaan')),
                ('kode_pos', models.IntegerField(default=None, verbose_name='Kode Pos')),
                ('lokasi', models.CharField(default=None, max_length=255, verbose_name='Lokasi')),
                ('latitude', models.CharField(default=None, max_length=255, verbose_name='Latitude')),
                ('longitude', models.CharField(default=None, max_length=255, verbose_name='longitude')),
                ('keterangan', models.CharField(max_length=4000, verbose_name='Keterangan')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('number', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='Update Terakhir')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=255, verbose_name='Deskripsi')),
                ('kode', models.IntegerField(verbose_name='Movement Type')),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='Update Terakhir')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.IntegerField(verbose_name='Kode Material')),
                ('deskripsi', models.CharField(max_length=255, verbose_name='Deskripsi')),
                ('kategori', models.CharField(max_length=255, verbose_name='Kategori')),
                ('informasi', models.TextField(max_length=4000, verbose_name='Informasi')),
                ('nama_kelompok', models.CharField(max_length=255, verbose_name='Nama Kelompok')),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='Update Terakhir')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
