# Generated by Django 2.2.4 on 2020-01-27 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_tanggal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(verbose_name='Tahun')),
                ('posting_date', models.DateTimeField(verbose_name='posting_date')),
                ('material', models.CharField(max_length=255, verbose_name='Material')),
                ('kategori', models.CharField(max_length=255, verbose_name='Kategori')),
                ('plant', models.CharField(max_length=255, verbose_name='Plant')),
                ('receiving_plant', models.CharField(max_length=255, verbose_name='Receiving Plant')),
                ('description', models.TextField(max_length=4000, verbose_name='Description')),
                ('value', models.FloatField(verbose_name='Value')),
                ('confirm', models.BooleanField(verbose_name='Konfirmasi')),
                ('valid', models.BooleanField(verbose_name='Validasi')),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='Update Terakhir')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='data_tahun_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(verbose_name='Tahun')),
                ('bulan', models.IntegerField(verbose_name='Bulan')),
                ('material', models.CharField(max_length=255, verbose_name='Material')),
                ('data', models.TextField(verbose_name='Description')),
                ('confirm', models.BooleanField(verbose_name='Konfirmasi')),
                ('valid', models.BooleanField(verbose_name='Validasi')),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='Update Terakhir')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='data_bulan_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(verbose_name='Tahun')),
                ('bulan', models.IntegerField(verbose_name='Bulan')),
                ('material', models.CharField(max_length=255, verbose_name='Material')),
                ('data', models.TextField(verbose_name='Description')),
                ('confirm', models.BooleanField(verbose_name='Konfirmasi')),
                ('valid', models.BooleanField(verbose_name='Validasi')),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='Update Terakhir')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
