# Generated by Django 2.2.4 on 2020-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_data_tahun_html_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_pemakain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(verbose_name='Tahun')),
                ('bulan', models.IntegerField(verbose_name='Bulan')),
                ('material', models.CharField(max_length=255, verbose_name='Material')),
                ('plant', models.CharField(max_length=255, verbose_name='Plant')),
                ('value', models.FloatField(verbose_name='Value')),
            ],
        ),
    ]
