# Generated by Django 2.2.4 on 2020-03-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_data_pemakain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notulensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.BooleanField(verbose_name='Lock')),
                ('tahun', models.IntegerField(verbose_name='Tahun')),
                ('bulan', models.IntegerField(verbose_name='Bulan')),
                ('nomor', models.CharField(max_length=255, verbose_name='Nomor')),
                ('hari_tanggal', models.CharField(max_length=255, verbose_name='Hari_tanggal')),
                ('pukul', models.CharField(max_length=255, verbose_name='Pukul')),
                ('hal', models.CharField(max_length=255, verbose_name='Hal')),
                ('info', models.CharField(max_length=255, verbose_name='Info')),
                ('pimpinan_rapat', models.CharField(max_length=255, verbose_name='Pimpinan_rapat')),
                ('notulis', models.CharField(max_length=255, verbose_name='Notulis')),
                ('jabatan', models.CharField(max_length=255, verbose_name='Jabatan')),
                ('nama_pimpinan', models.CharField(max_length=255, verbose_name='Nama_pimpinan')),
                ('perihal', models.TextField(verbose_name='Perihal')),
                ('perhatian', models.TextField(verbose_name='Perhatian')),
                ('rekons', models.TextField(verbose_name='Rekons')),
                ('catatan', models.TextField(verbose_name='Catatan')),
                ('hal_disampaikan', models.TextField(verbose_name='Hal_disampaikan')),
                ('bertanda_bintang', models.TextField(verbose_name='Bertanda_bintang')),
            ],
        ),
    ]
