# Generated by Django 2.2.4 on 2020-03-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='notulensi',
            name='ruang',
            field=models.CharField(default='', max_length=255, verbose_name='Hari_tanggal'),
            preserve_default=False,
        ),
    ]
