# Generated by Django 2.2.4 on 2020-03-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_notulensi_ruang'),
    ]

    operations = [
        migrations.AddField(
            model_name='notulensi',
            name='total',
            field=models.CharField(default='', max_length=255, verbose_name='total'),
            preserve_default=False,
        ),
    ]
