# Generated by Django 2.2.4 on 2020-03-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_notulensi_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='notulensi',
            name='distribusi',
            field=models.TextField(default='', verbose_name='Distribusi'),
            preserve_default=False,
        ),
    ]
