# Generated by Django 2.2.4 on 2020-03-25 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_notulensi_distribusi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('kontak', models.CharField(max_length=100)),
                ('current_latitude', models.FloatField()),
                ('current_longitude', models.FloatField()),
                ('current_directions', models.FloatField()),
                ('current_speed', models.FloatField()),
                ('time_step', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('last_accumulate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('directions', models.FloatField()),
                ('speed', models.FloatField()),
                ('distance', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('time_step', models.FloatField()),
                ('time', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='DataAnalize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_estimate', models.FloatField()),
                ('cost_real', models.FloatField()),
                ('revenue', models.FloatField()),
                ('score', models.FloatField()),
                ('time', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.Unit')),
            ],
        ),
    ]
